import React from 'react';
import { Sparkles, TrendingUp, Award, Target, Calendar } from 'lucide-react';

const AIReportCard = ({ report, loading }) => {
    if (loading) {
        return (
            <div className="glass-card" style={{ padding: '24px', marginBottom: '24px', textAlign: 'center' }}>
                <Sparkles className="spin" size={32} color="#667eea" style={{ marginBottom: '16px' }} />
                <h3>Generating Your Weekly Report...</h3>
                <p style={{ opacity: 0.6 }}>Analyzing your habits and finances to give you personalized insights.</p>
                <style>{`
                    .spin { animation: spin 2s linear infinite; }
                    @keyframes spin { 100% { transform: rotate(360deg); } }
                `}</style>
            </div>
        );
    }

    if (!report) return null;

    return (
        <div className="glass-card" style={{ padding: '24px', marginBottom: '24px', position: 'relative', overflow: 'hidden' }}>
            <div style={{
                position: 'absolute', top: 0, left: 0, right: 0, height: '6px',
                background: 'linear-gradient(90deg, #667eea 0%, #764ba2 100%)'
            }} />

            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '20px' }}>
                <div>
                    <h2 style={{ fontSize: '20px', fontWeight: '700', display: 'flex', alignItems: 'center', gap: '8px' }}>
                        <Sparkles size={20} color="#667eea" />
                        Weekly Insights
                    </h2>
                    <p style={{ fontSize: '13px', opacity: 0.6, marginTop: '4px' }}>
                        Generated by AI • {new Date().toLocaleDateString()}
                    </p>
                </div>
                <div style={{
                    background: 'rgba(102, 126, 234, 0.1)', color: '#667eea',
                    padding: '8px 16px', borderRadius: '20px', fontWeight: '700', fontSize: '24px'
                }}>
                    {report.score}<span style={{ fontSize: '14px' }}>/100</span>
                </div>
            </div>

            <p style={{ fontSize: '16px', lineHeight: '1.6', marginBottom: '24px', fontStyle: 'italic', color: '#4a5568' }}>
                "{report.summary}"
            </p>

            <div style={{ display: 'grid', gap: '16px', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))' }}>
                <div style={{ background: 'rgba(255,255,255,0.5)', padding: '16px', borderRadius: '12px' }}>
                    <h3 style={{ fontSize: '14px', fontWeight: '600', marginBottom: '12px', display: 'flex', alignItems: 'center', gap: '8px' }}>
                        <Award size={16} color="#f6ad55" /> Highlights
                    </h3>
                    <ul style={{ paddingLeft: '20px', margin: 0, fontSize: '14px', lineHeight: '1.5', color: '#4a5568' }}>
                        {report.highlights?.map((h, i) => <li key={i}>{h}</li>)}
                    </ul>
                </div>

                <div style={{ background: 'rgba(255,255,255,0.5)', padding: '16px', borderRadius: '12px' }}>
                    <h3 style={{ fontSize: '14px', fontWeight: '600', marginBottom: '12px', display: 'flex', alignItems: 'center', gap: '8px' }}>
                        <TrendingUp size={16} color="#48bb78" /> Analysis
                    </h3>
                    <div style={{ display: 'flex', flexDirection: 'column', gap: '8px', fontSize: '14px', color: '#4a5568' }}>
                        <p><strong>Spending:</strong> {report.spendingAnalysis}</p>
                        <p><strong>Habits:</strong> {report.habitAnalysis}</p>
                        {report.journalInsight && <p><strong>Mindset:</strong> {report.journalInsight}</p>}
                    </div>
                </div>
            </div>

            <div style={{ marginTop: '20px', padding: '16px', background: 'linear-gradient(135deg, rgba(102, 126, 234, 0.1) 0%, rgba(118, 75, 162, 0.1) 100%)', borderRadius: '12px', display: 'flex', gap: '12px', alignItems: 'center' }}>
                <Target size={24} color="#764ba2" />
                <div>
                    <h4 style={{ fontSize: '14px', fontWeight: '700', color: '#764ba2', marginBottom: '2px' }}>Focus for Next Week</h4>
                    <p style={{ fontSize: '14px', color: '#4a5568' }}>{report.suggestion}</p>
                </div>
            </div>
        </div>
    );
};

export default AIReportCard;
